export const socialSites = [
  {
    id: 1,
    username: '@nathanf',
    total: '1987',
    subName: 'followers',
    dailyChange: '12',
    increasedChange: true,
    logo: './images/icon-facebook.svg',
  },
  {
    id: 2,
    username: '@nathanf',
    total: '1044',
    subName: 'followers',
    dailyChange: '99',
    increasedChange: true,
    logo: './images/icon-twitter.svg',
  },
  {
    id: 3,
    username: '@realnathanf',
    total: '11k',
    subName: 'followers',
    dailyChange: '1099',
    increasedChange: true,
    logo: './images/icon-instagram.svg',
  },
  {
    id: 4,
    username: 'Nathan F.',
    total: '8239',
    subName: 'subscribers',
    dailyChange: '144',
    increasedChange: false,
    logo: './images/icon-youtube.svg',
  },
];

export const dailyOverview = [
  {
    id: 1,
    infoType: 'Page Views',
    count: '87',
    dailyChange: '3%',
    increasedChange: true,
    logo: './images/icon-facebook.svg',
  },
  {
    id: 2,
    infoType: 'Likes',
    count: '52',
    dailyChange: '2%',
    increasedChange: false,
    logo: './images/icon-facebook.svg',
  },
  {
    id: 3,
    infoType: 'Likes',
    count: '5462',
    dailyChange: '2257%',
    increasedChange: true,
    logo: './images/icon-instagram.svg',
  },
  {
    id: 4,
    infoType: 'Profile Views',
    count: '52k',
    dailyChange: '1375%',
    increasedChange: true,
    logo: './images/icon-instagram.svg',
  },
  {
    id: 5,
    infoType: 'Retweets',
    count: '117',
    dailyChange: '303%',
    increasedChange: true,
    logo: './images/icon-twitter.svg',
  },
  {
    id: 6,
    infoType: 'likes',
    count: '507',
    dailyChange: '553%',
    increasedChange: true,
    logo: './images/icon-twitter.svg',
  },
  {
    id: 7,
    infoType: 'Likes',
    count: '107',
    dailyChange: '19%',
    increasedChange: false,
    logo: './images/icon-youtube.svg',
  },
  {
    id: 8,
    infoType: 'Total Views',
    count: '1407',
    dailyChange: '12%',
    increasedChange: false,
    logo: './images/icon-youtube.svg',
  },
];
